// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATJf3p-fFY7FrugYWqZlmFdTCdaIeCrTM',
    appId: '1:712940500841:web:f7171a0ab68c5fa8c82ff8',
    messagingSenderId: '712940500841',
    projectId: 'eventapp-65ae8',
    authDomain: 'eventapp-65ae8.firebaseapp.com',
    storageBucket: 'eventapp-65ae8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMCSjJ3ZHiuuI-d3cZZqVHMpHMWtxQCSE',
    appId: '1:712940500841:android:a048590a4e4d6d07c82ff8',
    messagingSenderId: '712940500841',
    projectId: 'eventapp-65ae8',
    storageBucket: 'eventapp-65ae8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbL7cOCY3UR737MhB7H3hvuNxJV3KenWU',
    appId: '1:712940500841:ios:150526c5ef4c194fc82ff8',
    messagingSenderId: '712940500841',
    projectId: 'eventapp-65ae8',
    storageBucket: 'eventapp-65ae8.firebasestorage.app',
    iosBundleId: 'com.example.eventapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbL7cOCY3UR737MhB7H3hvuNxJV3KenWU',
    appId: '1:712940500841:ios:150526c5ef4c194fc82ff8',
    messagingSenderId: '712940500841',
    projectId: 'eventapp-65ae8',
    storageBucket: 'eventapp-65ae8.firebasestorage.app',
    iosBundleId: 'com.example.eventapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATJf3p-fFY7FrugYWqZlmFdTCdaIeCrTM',
    appId: '1:712940500841:web:9adaf21c00407bc6c82ff8',
    messagingSenderId: '712940500841',
    projectId: 'eventapp-65ae8',
    authDomain: 'eventapp-65ae8.firebaseapp.com',
    storageBucket: 'eventapp-65ae8.firebasestorage.app',
  );
}
